#! /bin/bash
# Azura : Complément à cards permettant de gérer les paquets provenant du NCR ( Nutyx Community Repository ).
# Ajout d'un paquet provenant du NCR 
echo "Êtes vous sūr de vouloir poursuivre"


# Suppression d'un paquet provenant du NCR 

# Afficher des informations sur le paquet sélectionné.

# Chercher un paquet dans le dépôt NCR 

#

