#! /bin/bash
# Azura : A cards complement build for manage package from the NCR( Nutyx Community Repository ).

# Function help 
function help () {
        echo -e " azura install : installer des paquets "
        echo -e " azura compile : compile un logiciel depuis son pkgfile "
        echo -e " azura remove : supprime le paquet en question "
        echo -e " azura info : affiche les informations connu sur le pkgfile "
}

# Add a package from the NCR 
function install () { 
        echo " Verification de la présence des outils de dev "
        echo " Tous les outils sont bien présents, début du processus d'Installation, veuillez patienter "
	

# Remove a package from the NCR 
function remove () { 

# Show information about the package 
function info () {

# Search a package in the NCR 
function search () { 

# Stop if error 
function stop_if_error(){
	if [[ $2 != 0 ]]; then
		write_log "${1} : Code Erreur $3"
		exit $3
	                      
}

# If error on syntax show help 
function main(){
	if [[ $# = 0 ]];then
		help
}

# Fonction main 
function main () {
         if [[ $# = 0 ]];then
		help
       


main $@
