#! /bin/bash
# Azura : Complément à cards permettant de gérer les paquets provenant du NCR ( Nutyx Community Repository ).
help () {
        echo -e " azura install : installer des paquets "
        echo -e " azura compile : compile un logiciel depuis son pkgfile "
        echo -e " azura remove : supprime le paquet en question "
# Ajout d'un paquet provenant du NCR 



# Suppression d'un paquet provenant du NCR 

# Afficher des informations sur le paquet sélectionné.

# Chercher un paquet dans le dépôt NCR 

#

