#! /bin/bash
# Azura : Complément à cards permettant de gérer les paquets provenant du NCR ( Nutyx Community Repository ).
# Ajout d'un paquet provenant du NCR 

# Suppression d'un paquet provenant du NCR 

# 

