#! /bin/bash
# Azura : Complément à cards permettant de gérer les paquets provenant du NCR ( Nutyx Community Repository ).

# Fonction help 

function help () {
        echo -e " azura install : installer des paquets "
        echo -e " azura compile : compile un logiciel depuis son pkgfile "
        echo -e " azura remove : supprime le paquet en question "
        echo -e " azura info : affiche les informations connu sur le pkgfile "
}

# Ajout d'un paquet provenant du NCR 
function install () { 
	if [ -z $1 ]; then
		_information $AZURA_PREFIX "Installation du paquet ${AZURA_PACKAGE}"
		mkdir $AZURA_DB/$AZURA_PACKAGE
		if [ $? != 0 ]; then
			_error $AZURA_PREFIX "Il est impossible de créer le dossier du paquet dans la base de donnée"
			exit 4
		fi
		_information $AZURA_PREFIX "Décompression du paquet binaire"
		tar --no-same-owner -xaf $AZURA_PKG/$AZURA_PACKAGE/$AZURA_PACKGE*.tar.zst -C /
		mv /.PACKTREE $YAMU_DB/$YAMU_PACKAGE
		mv /.PACKMETA $YAMU_DB/$YAMU_PACKAGE
	else
		_information $YAMU_PREFIX "Installation du paquet $1"
		mkdir $YAMU_DB/$1
		if [ $? != 0 ]; then
			_error $YAMU_PREFIX "Il est impossible de créer le dossier du paquet dans la base de donnée"
			exit 4
		fi
		_information $YAMU_PREFIX "Décompression du paquet binaire"
		tar --no-same-owner -xaf $YAMU_PKG/$1/$YAMU_PACKGE*.tar.zst -C /
		mv /.PACKTREE $YAMU_DB/$1
		mv /.PACKMETA $YAMU_DB/$1
	fi
	ldconfig -r /
}







         



# Suppression d'un paquet provenant du NCR 
function remove () { 

# Afficher des informations sur le paquet sélectionné.
function info () {

# Chercher un paquet dans le dépôt NCR 
function search () { 

#

