#! /bin/bash
# Azura : A cards complement build for manage package from the NCR( Nutyx Community Repository ).

# It's devel by Delta, an official member of the NuTyX Devel Team for the community 

# Function help 
function help () {
        echo -e " azura compile : compile a software from its pkgfile "
        echo -e " azura remove : remove the package "
        echo -e " azura info : show the information about the package "
}

# Add a package from the NCR 
function compile () { 
        echo " Verification of the cards devel utils "
        echo " All cards devel programs are installed, start the installation process, please wait "
	

# Remove a package from the NCR 
function remove () { 

# Show information about the package 
function info () {

# Search a package in the NCR 
function search () { 

# Stop if error 
function stop_if_error(){
	if [[ $2 != 0 ]]; then
		write_log "${1} : Code Erreur $3"
		exit $3
	                      
}

# If error on syntax show help 
	if [[ $# = 0 ]];then
		help
}

# Function main 
function main () {
if [ "$OPT_MODE" = "compile" ]; then
	       compile
elif [ "$OPT_MODE" = "help" ]; then
	        help
main $@

# End of Azura code.
# Thanks to all the contributors 
