#!/usr/bin/env python3

# This program is devel by The NuTyX Community, it's a translation to Azura official code in Pyhton.
# Azura it's by and for the community, everybody can contribute or fork the code 

# This is a test to Azura tools syncronisation of a database in python, if this is a good tools maybe it will be add on official devel branche 

# Help for azura 
def help () :
  print ("azura sync : syncronyse database from NCR") 
  print ("azura compile : compile the pkgfile")
  print ("azura remove : remove the package")

# Function update_database 
def update_database 
  print ("Mise à jour de la base de donnée")
  print ("The azura devel team doesn't have finish the program. Please go at the following link to discover new releases, features and news about the NCR's packages:https://docs.google.com/document/d/1dwCz1UFBhjnrxwuYiEUMUQGnlfNslhX1Bt0FNT9QMPc/edit?usp=sharing ")
# About
def about () :
  print ("Azura is devel by NuTyX community and Delta (a member of NuTyX team), it will manage all package from the NCR")

# If error of syntax show help
  
# Function 
def main () :
  if args == "about":
    about
  if args == "update_data":
    update_database
  if args == "help":
    help
        
 
        
  
  
  # End of file (test in python language)
  # Thanks to all the contributors 
  
